# Generated by Django 5.0.6 on 2024-06-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=150)),
                ('last_names', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=14, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=110, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('id_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
        ),
    ]
