# Generated by Django 5.0.6 on 2024-07-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_addresses_cities_countries_departments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
