# Generated by Django 5.0.6 on 2024-07-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_onetimepassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneTimePassword',
            new_name='otps',
        ),
    ]
