# Generated by Django 5.0.6 on 2024-07-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_onetimepassword_otps'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otps',
            table='otps',
        ),
    ]
