# Generated by Django 5.0.6 on 2024-06-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['role'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=150)),
                ('last_names', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=14, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=110, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id_number', 'email'],
                'managed': False,
            },
        ),
    ]
