# Generated by Django 5.0.6 on 2024-07-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bids',
                'managed': False,
            },
        ),
    ]
