# Generated by Django 5.0.6 on 2024-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
    ]
